# Generated by Django 5.1 on 2024-08-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vibe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvibe',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
