# Generated by Django 5.1 on 2024-08-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vibe', '0002_alter_dailyvibe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvibe',
            name='journal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
